#!/usr/bin/env node
// ============================================================================
// Precompile the JSX so browsers don't have to.
//
//   node tools/build.cjs
//
// The app has no bundler by design: index.html fetches the .jsx and runs Babel
// in the browser. That costs seconds of CPU on every page load for ~780 KB of
// source. This script does the same transform ahead of time and writes a
// .compiled.js next to each source file.
//
// STALENESS IS IMPOSSIBLE BY CONSTRUCTION. Each compiled file carries a hash of
// the exact source it came from, on line 1. At load time index.html hashes the
// .jsx it fetched and only uses the compiled bundle when the hashes agree —
// otherwise it silently falls back to compiling in the browser. So forgetting to
// run this script never ships stale code; it just gives up the speedup. That
// makes the compiled files a pure cache, safe to delete and safe to ignore.
//
// Run it before committing a release (and after any .jsx edit, to get the speed
// back). It uses the SAME vendored Babel the browser uses, so output is
// byte-identical to what the runtime path would have produced.
// ============================================================================
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
// Desktop only. mobile.html compiles with a different preset set (['env','react'])
// and its source is ~38 KB, where in-browser compilation is imperceptible — so it
// keeps the simple runtime path and needs no build step.
const TARGETS = ['retirement-planner.jsx'];

// FNV-1a, 32-bit. Must match the hashSource() function in index.html / mobile.html.
// Not cryptographic — it only needs to detect "this file changed", and it has to
// be fast enough to run on ~780 KB in the browser without a perceptible pause.
function hashSource(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
  }
  return h.toString(16);
}

// Load the vendored Babel in an isolated context (it expects a browser global).
const sandbox = {};
sandbox.window = sandbox;
sandbox.self = sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'vendor', 'babel.min.js'), 'utf8'), sandbox);

let failed = false;
for (const file of TARGETS) {
  const srcPath = path.join(ROOT, file);
  if (!fs.existsSync(srcPath)) {
    console.error(`  skip  ${file} (not found)`);
    continue;
  }
  const src = fs.readFileSync(srcPath, 'utf8');
  let code;
  try {
    code = sandbox.Babel.transform(src, { presets: ['react'] }).code;
  } catch (e) {
    console.error(`  FAIL  ${file}: ${e.message}`);
    failed = true;
    continue;
  }
  // Same two strips the runtime path applies: the React/Recharts destructuring
  // lines are replaced by the `globals` prelude injected at eval time.
  code = code.replace(/^.*useState.*useMemo.*useEffect.*=\s*React;?\s*$/m, '');
  code = code.replace(/^.*LineChart.*BarChart.*=\s*Recharts;?\s*$/m, '');

  const outPath = srcPath.replace(/\.jsx$/, '.compiled.js');
  const header = `//# planner-src-hash=${hashSource(src)}\n`
    + `// GENERATED by tools/build.cjs from ${file} — do not edit.\n`
    + `// Loaded only when the hash above matches the .jsx actually served; otherwise\n`
    + `// the browser recompiles from source, so this file can never go stale.\n`;
  fs.writeFileSync(outPath, header + code);
  const kb = (s) => Math.round(s.length / 1024);
  console.log(`  built ${path.basename(outPath)}  (${kb(src)} KB source -> ${kb(code)} KB compiled)`);
}

if (failed) process.exit(1);
console.log('\nDone. Commit the .compiled.js files alongside the source.');
