#!/usr/bin/env node
// ============================================================================
// Build the pages' code and stylesheet so browsers don't have to.
//
//   npm install          (once — Tailwind, used only here)
//   node tools/build.cjs
//
// There is no bundler. This script:
//   1. precompiles retirement-planner.jsx and retirement-planner-mobile.jsx to
//      .compiled.js files with the vendored Babel, so the output is identical to
//      what the browser would have produced;
//   2. builds app.css with the same Tailwind version the pages used to run in
//      the browser;
//   3. stamps each page with the source hash its bundle was built from, the
//      palette tokens, and a Content-Security-Policy.
//
// On the live site the pages trust the stamp and load only the compiled app and
// the stylesheet — no .jsx, no 3 MB compiler, no in-browser Tailwind. A stale
// build cannot reach the live site: the suite fails if any stamp, compiled file
// or app.css disagrees with its source. Served locally, the pages also hash the
// .jsx they fetch, so an edit made without rebuilding is compiled in the
// browser rather than ignored.
// ============================================================================
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
// Both apps. The phone was left to compile in the browser because its source
// was small — but that meant every phone downloaded the 3 MB Babel compiler to
// compile 60 KB, which is the worst trade on the slowest connection. Each
// target keeps the presets its page used at runtime, so output is identical.
const TARGETS = [
  { file: 'retirement-planner.jsx', presets: ['react'], stripGlobals: true, page: 'index.html' },
  { file: 'retirement-planner-mobile.jsx', presets: ['env', 'react'], stripGlobals: false, page: 'mobile.html' },
];

// FNV-1a, 32-bit. Must match the hashSource() function in index.html / mobile.html.
// Not cryptographic — it only needs to detect "this file changed", and it has to
// be fast enough to run on ~780 KB in the browser without a perceptible pause.
function hashSource(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
  }
  return h.toString(16);
}

// Load the vendored Babel in an isolated context (it expects a browser global).
const sandbox = {};
sandbox.window = sandbox;
sandbox.self = sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'vendor', 'babel.min.js'), 'utf8'), sandbox);

let failed = false;
const builtHashes = {};   // file -> source hash, stamped into its page below
for (const { file, presets, stripGlobals } of TARGETS) {
  const srcPath = path.join(ROOT, file);
  if (!fs.existsSync(srcPath)) {
    console.error(`  skip  ${file} (not found)`);
    continue;
  }
  const src = fs.readFileSync(srcPath, 'utf8');
  let code;
  try {
    code = sandbox.Babel.transform(src, { presets }).code;
  } catch (e) {
    console.error(`  FAIL  ${file}: ${e.message}`);
    failed = true;
    continue;
  }
  // Same two strips the runtime path applies: the React/Recharts destructuring
  // lines are replaced by the `globals` prelude injected at eval time.
  if (stripGlobals) {
    code = code.replace(/^.*useState.*useMemo.*useEffect.*=\s*React;?\s*$/m, '');
    code = code.replace(/^.*LineChart.*BarChart.*=\s*Recharts;?\s*$/m, '');
  }
  builtHashes[file] = hashSource(src);

  const outPath = srcPath.replace(/\.jsx$/, '.compiled.js');
  const header = `//# planner-src-hash=${hashSource(src)}\n`
    + `// GENERATED by tools/build.cjs from ${file} — do not edit.\n`
    + `// Loaded only when the hash above matches the build stamp in the page (and,\n`
    + `// when served locally, the .jsx itself); otherwise the page recompiles.\n`;
  fs.writeFileSync(outPath, header + code);
  const kb = (s) => Math.round(s.length / 1024);
  console.log(`  built ${path.basename(outPath)}  (${kb(src)} KB source -> ${kb(code)} KB compiled)`);
}

// ---------------------------------------------------------------------------
// The stylesheet.
//
// The pages used to load Tailwind's in-browser compiler (vendor/tailwind.js,
// 400 KB) and generate every style on every visit. The same Tailwind version
// now runs here, once, over the same source, and writes app.css (under 50 KB).
// The in-browser compiler is kept only as a fallback for a source edited
// without rebuilding — see the loader in index.html.
//
// The CSS depends on which classes the source uses and on the palette, so its
// stamp is a hash of exactly those inputs. A test recomputes it and fails if
// app.css is stale.
// ---------------------------------------------------------------------------
const { spawnSync } = require('child_process');
const CSS_INPUTS = ['retirement-planner.jsx', 'retirement-planner-mobile.jsx', 'theme.js',
                    'tools/tailwind.config.cjs', 'tools/tailwind.input.css', 'tools/looks.css'];
const cssHash = hashSource(CSS_INPUTS.map(f => fs.readFileSync(path.join(ROOT, f), 'utf8')).join('\u0000'));
{
  const bin = path.join(ROOT, 'node_modules', '.bin', process.platform === 'win32' ? 'tailwindcss.cmd' : 'tailwindcss');
  if (!fs.existsSync(bin)) {
    console.error('  FAIL  app.css: Tailwind is not installed — run `npm install` once, then build again.');
    failed = true;
  } else {
    const out = path.join(ROOT, 'app.css');
    const r = spawnSync(bin, ['-c', path.join(ROOT, 'tools', 'tailwind.config.cjs'),
      '-i', path.join(ROOT, 'tools', 'tailwind.input.css'), '-o', out, '--minify'],
      { cwd: ROOT, encoding: 'utf8', shell: process.platform === 'win32' });
    if (r.status !== 0) {
      console.error('  FAIL  app.css: ' + (r.stderr || r.stdout || 'tailwindcss exited ' + r.status));
      failed = true;
    } else {
      const css = fs.readFileSync(out, 'utf8');
      fs.writeFileSync(out, `/*! planner-css-hash=${cssHash} — GENERATED by tools/build.cjs, do not edit. */\n` + css);
      console.log(`  built app.css  (${Math.round(css.length / 1024)} KB)`);
    }
  }
}

// ---------------------------------------------------------------------------
// The build stamp.
//
// Each page is told the hash of the source its compiled bundle was built from,
// and links the stylesheet by its hash. On the live site that is enough: the
// page loads the bundle and the stylesheet and nothing else — no .jsx, no
// compiler. Served from this machine (localhost), the page still fetches the
// .jsx and hashes it, so an edit made without rebuilding is compiled in the
// browser rather than ignored. A test fails the suite if any stamp is stale, so
// the live site cannot be handed a bundle that disagrees with its source.
// ---------------------------------------------------------------------------
const STAMP_OPEN = '<!-- BEGIN GENERATED BUILD STAMP (tools/build.cjs) -->';
const STAMP_CLOSE = '<!-- END GENERATED BUILD STAMP -->';
function stampBlock(file) {
  const stamp = { src: builtHashes[file], css: cssHash };
  return STAMP_OPEN + '\n'
    + `  <link rel="stylesheet" href="app.css?h=${cssHash}">\n`
    + `  <script>window.PLANNER_BUILD = ${JSON.stringify(stamp)};</script>\n  `
    + STAMP_CLOSE;
}
for (const { file, page } of TARGETS) {
  const htmlPath = path.join(ROOT, page);
  if (!fs.existsSync(htmlPath) || !builtHashes[file]) continue;
  const html = fs.readFileSync(htmlPath, 'utf8');
  const a = html.indexOf(STAMP_OPEN), b = html.indexOf(STAMP_CLOSE);
  if (a === -1 || b === -1) {
    console.error(`  FAIL  ${page}: build stamp markers not found`);
    failed = true;
    continue;
  }
  const next = html.slice(0, a) + stampBlock(file) + html.slice(b + STAMP_CLOSE.length);
  if (next !== html) { fs.writeFileSync(htmlPath, next); console.log(`  wrote build stamp into ${page}`); }
  else console.log(`  build stamp in ${page} already current`);
}

// ---------------------------------------------------------------------------
// The theme token block.
//
// Every Tailwind colour in the app resolves through a CSS custom property, and
// the values live in theme.js so the palette has one home. They have to reach
// the browser in the document HEAD, before first paint — a runtime injection
// would flash the wrong theme on load for anyone whose saved preference is
// light. So they are stamped into the HTML between markers here.
//
// Drift is caught rather than prevented: a test in the suite regenerates this
// block from theme.js and asserts the HTML still matches. Forgetting to run the
// build fails the suite instead of shipping a stale palette.
// ---------------------------------------------------------------------------
const theme = require(path.join(ROOT, 'theme.js'));
const { open: OPEN, close: CLOSE } = theme.HEAD_MARKERS;

for (const file of ['index.html', 'mobile.html']) {
  const htmlPath = path.join(ROOT, file);
  if (!fs.existsSync(htmlPath)) continue;
  const html = fs.readFileSync(htmlPath, 'utf8');
  const a = html.indexOf(OPEN), b = html.indexOf(CLOSE);
  if (a === -1 || b === -1) {
    console.error(`  FAIL  ${file}: theme token markers not found`);
    failed = true;
    continue;
  }
  const next = html.slice(0, a) + theme.headBlock() + html.slice(b + CLOSE.length);
  if (next !== html) {
    fs.writeFileSync(htmlPath, next);
    console.log(`  wrote theme tokens into ${file}`);
  } else {
    console.log(`  theme tokens in ${file} already current`);
  }
}

// ---------------------------------------------------------------------------
// The Content-Security-Policy meta tag.
//
// GitHub Pages sends no headers, so the policy is a <meta> at the top of each
// page. Scripts are allowed from the site itself and from Blob URLs (how the
// app's code runs — see index.html), never inline and never through eval; the
// page's own static inline scripts are allowed by SHA-256 hash, computed here
// from their exact text. Any edit to an inline script changes its hash, and a
// test regenerates this block and fails the suite if the HTML is stale.
// connect-src names the one host the AI assistant talks to.
// ---------------------------------------------------------------------------
const crypto = require('crypto');
const CSP_OPEN = '<!-- BEGIN GENERATED CSP (tools/build.cjs) -->';
const CSP_CLOSE = '<!-- END GENERATED CSP -->';
const CSP_CONNECT_HOSTS = ['https://api.anthropic.com'];
function inlineScriptHashes(html) {
  const out = [];
  const re = /<script(\s[^>]*)?>([\s\S]*?)<\/script>/g;
  // Comments first: a "<script>" mentioned in prose inside an HTML comment
  // would otherwise open a bogus block that swallows the next real script,
  // whose hash then never appears — and the browser blocks it.
  const stripped = html.replace(/<!--[\s\S]*?-->/g, '');
  let m;
  while ((m = re.exec(stripped))) {
    const attrs = m[1] || '';
    if (/\bsrc\s*=/.test(attrs)) continue;          // external — covered by 'self'
    if (/\btype\s*=\s*["']text\/babel/.test(attrs)) continue; // never executed as-is
    const body = m[2];
    if (!body.trim()) continue;
    out.push("'sha256-" + crypto.createHash('sha256').update(body, 'utf8').digest('base64') + "'");
  }
  return out;
}
function cspFor(html) {
  const hashes = inlineScriptHashes(html);
  return [
    "default-src 'self'",
    "script-src 'self' blob: " + hashes.join(' '),
    "worker-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self' " + CSP_CONNECT_HOSTS.join(' '),
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join('; ');
}
function cspBlock(html) {
  return CSP_OPEN + '\n  <meta http-equiv="Content-Security-Policy" content="' + cspFor(html) + '">\n  ' + CSP_CLOSE;
}
for (const file of ['index.html', 'mobile.html']) {
  const htmlPath = path.join(ROOT, file);
  if (!fs.existsSync(htmlPath)) continue;
  const html = fs.readFileSync(htmlPath, 'utf8');
  const a = html.indexOf(CSP_OPEN), b = html.indexOf(CSP_CLOSE);
  if (a === -1 || b === -1) {
    console.error(`  FAIL  ${file}: CSP markers not found`);
    failed = true;
    continue;
  }
  const next = html.slice(0, a) + cspBlock(html) + html.slice(b + CSP_CLOSE.length);
  if (next !== html) {
    fs.writeFileSync(htmlPath, next);
    console.log(`  wrote Content-Security-Policy into ${file} (${inlineScriptHashes(html).length} inline script hashes)`);
  } else {
    console.log(`  Content-Security-Policy in ${file} already current`);
  }
}
module.exports = { inlineScriptHashes, cspFor, CSP_OPEN, CSP_CLOSE, CSP_CONNECT_HOSTS,
                   hashSource, CSS_INPUTS, STAMP_OPEN, STAMP_CLOSE };

if (failed) process.exit(1);
console.log('\nDone. Commit the .compiled.js files and app.css alongside the source.');
